networks:
  localnet:
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf/:/etc/nginx/conf.d/default.conf
      #      - ./config/nginx.conf/:/etc/nginx/conf.d/nginx.conf
      - ./frontend/dist/frontend:/usr/share/nginx/html/
    ports:
      - "80:80"
    networks:
      localnet:
        ipv4_address: 10.0.0.2

  builder-be:
    image: backend-builder
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    networks:
      localnet:
        ipv4_address: 10.0.0.3

  backend:
    image: backend
    volumes:
      - ./frontend/src/assets:/assets
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - "8181:8181"
    depends_on:
      - builder-be
    #       - postgres
    environment:
      - SERVER_PORT=8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://87.249.49.62:5432/terrestrial_tutor
      - SPRING_DATASOURCE_USERNAME=tutor
      - SPRING_DATASOURCE_PASSWORD=tErRrEsTrIaLtUtOr
    networks:
      localnet:
        ipv4_address: 10.0.0.4

  frontend:
    image: node:18.20.1-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run watch"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      localnet:
        ipv4_address: 10.0.0.5

  #Uncomment if it's server
  postgres:
    image: postgres:16.1
    build:
      context: .
      dockerfile: Dockerfile
      target: postgres
    environment:
      POSTGRES_DB: terrestrial_tutor
      POSTGRES_PASSWORD: tErRrEsTrIaLtUtOr
      POSTGRES_USER: tutor
    #    command:
    #      - /bin/sh -c apt update && apt install cron
    ports:
      - '5432:5432'
    volumes:
      - ./db_snapshots/:/dumps
      - ./db_snapshots/init:/docker-entrypoint-initdb.d/

  postgres_dev:
    image: postgres
    environment:
      POSTGRES_DB: terrestrial_tutor
      POSTGRES_PASSWORD: tErRrEsTrIaLtUtOr
      POSTGRES_USER: tutor
    ports:
      - '5433:5432'
    volumes:
      - ./db_snapshots/:/dumps
      - ./db_snapshots/init/:/docker-entrypoint-initdb.d/
